//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\della\projects\compilers-final-work\Lang.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Grammar {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class LangLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		OE=1, CE=2, OB=3, CB=4, AT=5, PLUS=6, MINUS=7, MULT=8, DIV=9, AND=10, 
		OR=11, NOT=12, EQ=13, LT=14, GT=15, LE=16, GE=17, NE=18, BOOL_TRUE=19, 
		BOL_FALSE=20, IF=21, WHILE=22, DO=23, THEN=24, ELSE=25, WRITE=26, READ=27, 
		STR=28, EOL=29, NUM=30, VAR=31, COMMENT=32, WS=33;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"OE", "CE", "OB", "CB", "AT", "PLUS", "MINUS", "MULT", "DIV", "AND", "OR", 
		"NOT", "EQ", "LT", "GT", "LE", "GE", "NE", "BOOL_TRUE", "BOL_FALSE", "IF", 
		"WHILE", "DO", "THEN", "ELSE", "WRITE", "READ", "STR", "EOL", "NUM", "VAR", 
		"COMMENT", "WS"
	};


	public LangLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public LangLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'{'", "'}'", "'='", "'+'", "'-'", "'*'", "'/'", "'&&'", 
		"'||'", "'!'", "'=='", "'<'", "'>'", "'<='", "'>='", "'!='", "'true'", 
		"'false'", null, null, null, null, null, null, null, null, "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "OE", "CE", "OB", "CB", "AT", "PLUS", "MINUS", "MULT", "DIV", "AND", 
		"OR", "NOT", "EQ", "LT", "GT", "LE", "GE", "NE", "BOOL_TRUE", "BOL_FALSE", 
		"IF", "WHILE", "DO", "THEN", "ELSE", "WRITE", "READ", "STR", "EOL", "NUM", 
		"VAR", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Lang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static LangLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '#', '\xCA', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', 
		'\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', 
		'\x3', '\x1D', '\a', '\x1D', '\x9E', '\n', '\x1D', '\f', '\x1D', '\xE', 
		'\x1D', '\xA1', '\v', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', 
		'\x3', '\x1E', '\x3', '\x1F', '\x6', '\x1F', '\xA8', '\n', '\x1F', '\r', 
		'\x1F', '\xE', '\x1F', '\xA9', '\x3', '\x1F', '\x3', '\x1F', '\x6', '\x1F', 
		'\xAE', '\n', '\x1F', '\r', '\x1F', '\xE', '\x1F', '\xAF', '\x5', '\x1F', 
		'\xB2', '\n', '\x1F', '\x3', ' ', '\x6', ' ', '\xB5', '\n', ' ', '\r', 
		' ', '\xE', ' ', '\xB6', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', '!', 
		'\a', '!', '\xBD', '\n', '!', '\f', '!', '\xE', '!', '\xC0', '\v', '!', 
		'\x3', '!', '\x3', '!', '\x3', '\"', '\x6', '\"', '\xC5', '\n', '\"', 
		'\r', '\"', '\xE', '\"', '\xC6', '\x3', '\"', '\x3', '\"', '\x2', '\x2', 
		'#', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', 
		'\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', 
		'\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', 
		'\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', 
		'-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', 
		'\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '=', ' ', '?', '!', '\x41', 
		'\"', '\x43', '#', '\x3', '\x2', '\x14', '\x4', '\x2', 'K', 'K', 'k', 
		'k', '\x4', '\x2', 'H', 'H', 'h', 'h', '\x4', '\x2', 'Y', 'Y', 'y', 'y', 
		'\x4', '\x2', 'J', 'J', 'j', 'j', '\x4', '\x2', 'N', 'N', 'n', 'n', '\x4', 
		'\x2', 'G', 'G', 'g', 'g', '\x4', '\x2', '\x46', '\x46', '\x66', '\x66', 
		'\x4', '\x2', 'Q', 'Q', 'q', 'q', '\x4', '\x2', 'V', 'V', 'v', 'v', '\x4', 
		'\x2', 'P', 'P', 'p', 'p', '\x4', '\x2', 'U', 'U', 'u', 'u', '\x4', '\x2', 
		'T', 'T', 't', 't', '\x4', '\x2', '\x43', '\x43', '\x63', '\x63', '\x3', 
		'\x2', '$', '$', '\x3', '\x2', '\x32', ';', '\x4', '\x2', '\x43', '\\', 
		'\x63', '|', '\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x5', '\x2', '\v', 
		'\f', '\xF', '\xF', '\"', '\"', '\x2', '\xD0', '\x2', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', 
		'\x3', '\x2', '\x2', '\x2', '\x3', '\x45', '\x3', '\x2', '\x2', '\x2', 
		'\x5', 'G', '\x3', '\x2', '\x2', '\x2', '\a', 'I', '\x3', '\x2', '\x2', 
		'\x2', '\t', 'K', '\x3', '\x2', '\x2', '\x2', '\v', 'M', '\x3', '\x2', 
		'\x2', '\x2', '\r', 'O', '\x3', '\x2', '\x2', '\x2', '\xF', 'Q', '\x3', 
		'\x2', '\x2', '\x2', '\x11', 'S', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'U', '\x3', '\x2', '\x2', '\x2', '\x15', 'W', '\x3', '\x2', '\x2', '\x2', 
		'\x17', 'Z', '\x3', '\x2', '\x2', '\x2', '\x19', ']', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', '_', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x62', '\x3', 
		'\x2', '\x2', '\x2', '\x1F', '\x64', '\x3', '\x2', '\x2', '\x2', '!', 
		'\x66', '\x3', '\x2', '\x2', '\x2', '#', 'i', '\x3', '\x2', '\x2', '\x2', 
		'%', 'l', '\x3', '\x2', '\x2', '\x2', '\'', 'o', '\x3', '\x2', '\x2', 
		'\x2', ')', 't', '\x3', '\x2', '\x2', '\x2', '+', 'z', '\x3', '\x2', '\x2', 
		'\x2', '-', '}', '\x3', '\x2', '\x2', '\x2', '/', '\x83', '\x3', '\x2', 
		'\x2', '\x2', '\x31', '\x86', '\x3', '\x2', '\x2', '\x2', '\x33', '\x8B', 
		'\x3', '\x2', '\x2', '\x2', '\x35', '\x90', '\x3', '\x2', '\x2', '\x2', 
		'\x37', '\x96', '\x3', '\x2', '\x2', '\x2', '\x39', '\x9B', '\x3', '\x2', 
		'\x2', '\x2', ';', '\xA4', '\x3', '\x2', '\x2', '\x2', '=', '\xA7', '\x3', 
		'\x2', '\x2', '\x2', '?', '\xB4', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\xB8', '\x3', '\x2', '\x2', '\x2', '\x43', '\xC4', '\x3', '\x2', '\x2', 
		'\x2', '\x45', '\x46', '\a', '*', '\x2', '\x2', '\x46', '\x4', '\x3', 
		'\x2', '\x2', '\x2', 'G', 'H', '\a', '+', '\x2', '\x2', 'H', '\x6', '\x3', 
		'\x2', '\x2', '\x2', 'I', 'J', '\a', '}', '\x2', '\x2', 'J', '\b', '\x3', 
		'\x2', '\x2', '\x2', 'K', 'L', '\a', '\x7F', '\x2', '\x2', 'L', '\n', 
		'\x3', '\x2', '\x2', '\x2', 'M', 'N', '\a', '?', '\x2', '\x2', 'N', '\f', 
		'\x3', '\x2', '\x2', '\x2', 'O', 'P', '\a', '-', '\x2', '\x2', 'P', '\xE', 
		'\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\a', '/', '\x2', '\x2', 'R', '\x10', 
		'\x3', '\x2', '\x2', '\x2', 'S', 'T', '\a', ',', '\x2', '\x2', 'T', '\x12', 
		'\x3', '\x2', '\x2', '\x2', 'U', 'V', '\a', '\x31', '\x2', '\x2', 'V', 
		'\x14', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\a', '(', '\x2', '\x2', 
		'X', 'Y', '\a', '(', '\x2', '\x2', 'Y', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'Z', '[', '\a', '~', '\x2', '\x2', '[', '\\', '\a', '~', '\x2', '\x2', 
		'\\', '\x18', '\x3', '\x2', '\x2', '\x2', ']', '^', '\a', '#', '\x2', 
		'\x2', '^', '\x1A', '\x3', '\x2', '\x2', '\x2', '_', '`', '\a', '?', '\x2', 
		'\x2', '`', '\x61', '\a', '?', '\x2', '\x2', '\x61', '\x1C', '\x3', '\x2', 
		'\x2', '\x2', '\x62', '\x63', '\a', '>', '\x2', '\x2', '\x63', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', '@', '\x2', '\x2', '\x65', 
		' ', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', '\a', '>', '\x2', '\x2', 
		'g', 'h', '\a', '?', '\x2', '\x2', 'h', '\"', '\x3', '\x2', '\x2', '\x2', 
		'i', 'j', '\a', '@', '\x2', '\x2', 'j', 'k', '\a', '?', '\x2', '\x2', 
		'k', '$', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', '#', '\x2', '\x2', 
		'm', 'n', '\a', '?', '\x2', '\x2', 'n', '&', '\x3', '\x2', '\x2', '\x2', 
		'o', 'p', '\a', 'v', '\x2', '\x2', 'p', 'q', '\a', 't', '\x2', '\x2', 
		'q', 'r', '\a', 'w', '\x2', '\x2', 'r', 's', '\a', 'g', '\x2', '\x2', 
		's', '(', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', 'h', '\x2', '\x2', 
		'u', 'v', '\a', '\x63', '\x2', '\x2', 'v', 'w', '\a', 'n', '\x2', '\x2', 
		'w', 'x', '\a', 'u', '\x2', '\x2', 'x', 'y', '\a', 'g', '\x2', '\x2', 
		'y', '*', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\t', '\x2', '\x2', '\x2', 
		'{', '|', '\t', '\x3', '\x2', '\x2', '|', ',', '\x3', '\x2', '\x2', '\x2', 
		'}', '~', '\t', '\x4', '\x2', '\x2', '~', '\x7F', '\t', '\x5', '\x2', 
		'\x2', '\x7F', '\x80', '\t', '\x2', '\x2', '\x2', '\x80', '\x81', '\t', 
		'\x6', '\x2', '\x2', '\x81', '\x82', '\t', '\a', '\x2', '\x2', '\x82', 
		'.', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', '\t', '\b', '\x2', '\x2', 
		'\x84', '\x85', '\t', '\t', '\x2', '\x2', '\x85', '\x30', '\x3', '\x2', 
		'\x2', '\x2', '\x86', '\x87', '\t', '\n', '\x2', '\x2', '\x87', '\x88', 
		'\t', '\x5', '\x2', '\x2', '\x88', '\x89', '\t', '\a', '\x2', '\x2', '\x89', 
		'\x8A', '\t', '\v', '\x2', '\x2', '\x8A', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x8C', '\t', '\a', '\x2', '\x2', '\x8C', '\x8D', '\t', 
		'\x6', '\x2', '\x2', '\x8D', '\x8E', '\t', '\f', '\x2', '\x2', '\x8E', 
		'\x8F', '\t', '\a', '\x2', '\x2', '\x8F', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '\x90', '\x91', '\t', '\x4', '\x2', '\x2', '\x91', '\x92', '\t', 
		'\r', '\x2', '\x2', '\x92', '\x93', '\t', '\x2', '\x2', '\x2', '\x93', 
		'\x94', '\t', '\n', '\x2', '\x2', '\x94', '\x95', '\t', '\a', '\x2', '\x2', 
		'\x95', '\x36', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\t', '\r', 
		'\x2', '\x2', '\x97', '\x98', '\t', '\a', '\x2', '\x2', '\x98', '\x99', 
		'\t', '\xE', '\x2', '\x2', '\x99', '\x9A', '\t', '\b', '\x2', '\x2', '\x9A', 
		'\x38', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9F', '\a', '$', '\x2', 
		'\x2', '\x9C', '\x9E', '\n', '\xF', '\x2', '\x2', '\x9D', '\x9C', '\x3', 
		'\x2', '\x2', '\x2', '\x9E', '\xA1', '\x3', '\x2', '\x2', '\x2', '\x9F', 
		'\x9D', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', '\xA2', '\xA3', '\a', '$', '\x2', '\x2', '\xA3', 
		':', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\a', '=', '\x2', '\x2', 
		'\xA5', '<', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA8', '\t', '\x10', 
		'\x2', '\x2', '\xA7', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', 
		'\x3', '\x2', '\x2', '\x2', '\xA9', '\xA7', '\x3', '\x2', '\x2', '\x2', 
		'\xA9', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xB1', '\x3', '\x2', 
		'\x2', '\x2', '\xAB', '\xAD', '\v', '\x2', '\x2', '\x2', '\xAC', '\xAE', 
		'\t', '\x10', '\x2', '\x2', '\xAD', '\xAC', '\x3', '\x2', '\x2', '\x2', 
		'\xAE', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xAD', '\x3', '\x2', 
		'\x2', '\x2', '\xAF', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB2', 
		'\x3', '\x2', '\x2', '\x2', '\xB1', '\xAB', '\x3', '\x2', '\x2', '\x2', 
		'\xB1', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB2', '>', '\x3', '\x2', 
		'\x2', '\x2', '\xB3', '\xB5', '\t', '\x11', '\x2', '\x2', '\xB4', '\xB3', 
		'\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\x3', '\x2', '\x2', '\x2', 
		'\xB6', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', '\x3', '\x2', 
		'\x2', '\x2', '\xB7', '@', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB9', 
		'\a', '\x31', '\x2', '\x2', '\xB9', '\xBA', '\a', '\x31', '\x2', '\x2', 
		'\xBA', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBD', '\n', '\x12', 
		'\x2', '\x2', '\xBC', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xC0', 
		'\x3', '\x2', '\x2', '\x2', '\xBE', '\xBC', '\x3', '\x2', '\x2', '\x2', 
		'\xBE', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC1', '\x3', '\x2', 
		'\x2', '\x2', '\xC0', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xC2', 
		'\b', '!', '\x2', '\x2', '\xC2', '\x42', '\x3', '\x2', '\x2', '\x2', '\xC3', 
		'\xC5', '\t', '\x13', '\x2', '\x2', '\xC4', '\xC3', '\x3', '\x2', '\x2', 
		'\x2', '\xC5', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC4', '\x3', 
		'\x2', '\x2', '\x2', '\xC6', '\xC7', '\x3', '\x2', '\x2', '\x2', '\xC7', 
		'\xC8', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC9', '\b', '\"', '\x2', 
		'\x2', '\xC9', '\x44', '\x3', '\x2', '\x2', '\x2', '\n', '\x2', '\x9F', 
		'\xA9', '\xAF', '\xB1', '\xB6', '\xBE', '\xC6', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Grammar
